name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 18.x
    - run: npm i
    - run: |
        echo ">>> Start compile vscode-office-lite."
        npm run build
        echo ">>> Compile vscode-office-lite sucess!"